branches/Sztek/Backup/Sztek/Controllers/ToplistController.cs
using System;
using System.Collections.Generic;
using System.EnterpriseServices;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Sztek.Models;

namespace Sztek.Controllers
{
    public class ToplistController : Controller
    {
        //
        // GET: /TopList/
        private readonly DatabaseEntities _entities = new DatabaseEntities();
        public ActionResult Index()
        {
            var current = _entities.Users.FirstOrDefault(us => us.username == User.Identity.Name);
            if (current == null)
                return RedirectToAction("NotLoggedIn", "Home");

            var users = _entities.Users.Include("results").ToList();
            var toplists = (from user in users
                let score = user.results.Sum(x => x.score)
                select new toplistModel
                {
                    Name = user.username,
                    Country = user.country,
                    Id = user.id,
                    Score = score
                }).OrderByDescending(x => x.Score).ThenBy(x => x.Name).ToList();
            for (var i = 0; i < toplists.Count; i++)
            {
                toplists[i].Place = i + 1;
            }

            return View(toplists);
        }

        

    }
}

branches/Sztek/Backup/Sztek/Views/Shared/NotLoggedIn.cshtml
@{
    ViewBag.Title = "Hiba";
}

<h2>Hiba!</h2>
<p>Ez az oldal csak bejelentkezés után tekinthető meg.</p>

branches/Sztek/Backup/Sztek/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Tank Játék Online</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        <script src="~/Scripts/removeAd.js"></script>

    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Tank Játék Online", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Kezdőlap", "Index", "Home")</li>
                            <li>@Html.ActionLink("Váróterem", "Lobby", "Home")</li>
                            <li>@Html.ActionLink("Toplista", "Index", "Toplist")</li>
                            <li>@Html.ActionLink("Info", "About", "Home")</li>
                            <li>@Html.ActionLink("Készítők", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Tank Játék Online</p>
                </div>
            </div>
        </footer>


        @RenderSection("scripts", required: false)

    </body>
</html>